version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:11
    working_directory: ~/repo
commands:
  npm_install:
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
              - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  tool_install:
    steps:
      - run: sudo npm i -g can-npm-publish
jobs:
  build: 
    executor: default
    steps:
      - npm_install
      - run:
          name: Run build
          command: npm build
      - persist_to_workspace:
          root: ~/repo
          paths: .
  publish:
    executor: default
    steps:
      - tool_install
      - attach_workspace:
          at: ~/repo
      - run: echo //registry.npmjs.org:_authToken=${NPM_TOKEN} > .npmrc
      - run:
          command: |
            if can-npm-publish; then
                npm publish
            else
                echo "publish skipped"
            fi
workflows:
  version: 2
  publishflow:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only:
                - master
